# Requires repo secret: PERSONAL_ACCESS_TOKEN with permissions:
#   Contents: read and write
#   Pull Requests: read and write

name: Dolphin Build

on:
  workflow_dispatch:
    inputs:
      dolphin_ref:
        description: 'Dolphin GitHub version tag (e.g. "2606")'
        required: true
        type: string
      auto-merge:
        description: 'Auto-merge pull request?'
        required: true
        type: boolean
        default: true
  push:
run-name: "${{ github.workflow }}: ${{ inputs.dolphin_ref || '(default version)' }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  dolphin_ref: ${{ inputs.dolphin_ref || '2606' }}
  igir_ref: ${{ github.head_ref || github.ref }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      major: ${{ steps.parse-version.outputs.major }}
      minor: ${{ steps.parse-version.outputs.minor }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dolphin-emu/dolphin
          ref: ${{ env.dolphin_ref }}
      - id: parse-version
        run: |
          set -euo pipefail
          echo "major=$(grep 'set(DOLPHIN_VERSION_MAJOR' CMake/ScmRevGen.cmake | sed -E 's/.*"([0-9]+)".*/\1/')" >> "${GITHUB_OUTPUT}"
          echo "minor=$(grep 'set(DOLPHIN_VERSION_MINOR' CMake/ScmRevGen.cmake | sed -E 's/.*"([0-9]+)".*/\1/')" >> "${GITHUB_OUTPUT}"

  build-windows:
    name: build-windows ${{ matrix.nodejs_arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x64
            nodejs_arch: x64
          - platform: ARM64
            nodejs_arch: arm64
    # Dolphin v2606 requires VS 2022 (v143)
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dolphin-emu/dolphin
          ref: ${{ env.dolphin_ref }}
          submodules: 'recursive'
      - uses: microsoft/setup-msbuild@v2
      - name: Build
        run: |
          msbuild Source/dolphin-emu.sln -maxcpucount /property:Configuration=Release "/property:Platform=${{ matrix.platform }}"
          Get-ChildItem -Path Binary\* -Recurse
          Move-Item -Path Binary\*\DolphinTool.exe -Destination .\
      - name: Rename binary
        run: |
          $Dir = "artifacts\packages\dolphin-tool-win32-${{ matrix.nodejs_arch }}"
          mkdir "$Dir"
          mv DolphinTool.exe "$Dir\DolphinTool.exe"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.nodejs_arch }}-${{ github.sha }}
          path: artifacts/**/DolphinTool.exe
          if-no-files-found: error
