name: Dolphin Build

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOLPHIN_REF: ${{ inputs.dolphin_ref || 'master' }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dolphin-emu/dolphin
          ref: ${{ env.DOLPHIN_REF }}
          submodules: true
      - run: |
          sudo apt-get update
          sudo apt-get install -y xi
          cmake . -DLINUX_LOCAL_DEV=true
          make -j $(nproc)

